# Generated by Django 4.0.4 on 2022-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
